[package]
name = "funky-subtitles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
braille = "1.0.3"
image = "0.24.8"
itertools = "0.12.0"
